export const GET_ARTICLES_REQUEST = 'GET_ARTICLES_REQUEST'
export const GET_ARTICLES_SUCCESS = 'GET_ARTICLES_SUCCESS'
export const GET_ARTICLES_FAILED = 'GET_ARTICLES_FAILED'

export const POST_LOGIN_REQUEST = 'POST_LOGIN_REQUEST'
export const POST_LOGIN_SUCCESS = 'POST_LOGIN_SUCCESS'
export const POST_LOGIN_FAILED = 'POST_LOGIN_FAILED'

export const POST_LOGOUT_REQUEST = 'POST_LOGOUT_REQUEST'
export const POST_LOGOUT_SUCCESS = 'POST_LOGOUT_SUCCESS'
export const POST_LOGOUT_FAILED = 'POST_LOGOUT_FAILED'

export const POST_SIGNUP_REQUEST = 'POST_SIGNUP_REQUEST'
export const POST_SIGNUP_SUCCESS = 'POST_SIGNUP_SUCCESS'
export const POST_SIGNUP_FAILED = 'POST_SIGNUP_FAILED'

export const FETCH_REQUEST = 'FETCH_REQUEST'
export const FETCH_SUCCESS = 'FETCH_SUCCESS'
export const FETCH_FAILED = 'FETCH_FAILED'

export const POST_UPLOAD_REQUEST = 'POST_UPLOAD_REQUEST'
export const POST_UPLOAD_SUCCESS = 'POST_UPLOAD_SUCCESS'
export const POST_UPLOAD_FAILED = 'POST_UPLOAD_FAILED'

export const GET_USERINFO_REQUEST = 'GET_USERINFO_REQUEST'
export const GET_USERINFO_SUCCESS = 'GET_USERINFO_SUCCESS'
export const GET_USERINFO_FAILED = 'GET_USERINFO_FAILED'

export const PUT_USERINFO_REQUEST = 'PUT_USERINFO_REQUEST'
export const PUT_USERINFO_SUCCESS = 'PUT_USERINFO_SUCCESS'
export const PUT_USERINFO_FAILED = 'PUT_USERINFO_FAILED'

export const POST_TEAMS_REQUEST = 'POST_TEAMS_REQUEST'
export const POST_TEAMS_SUCCESS = 'POST_TEAMS_SUCCESS'
export const POST_TEAMS_FAILED = 'POST_TEAMS_FAILED'

export const PUT_TEAMS_REQUEST = 'PUT_TEAMS_REQUEST'
export const PUT_TEAMS_SUCCESS = 'PUT_TEAMS_SUCCESS'
export const PUT_TEAMS_FAILED = 'PUT_TEAMS_FAILED'

export const GET_USER_TEAMS_REQUEST = 'GET_USER_TEAMS_REQUEST'
export const GET_USER_TEAMS_SUCCESS = 'GET_USER_TEAMS_SUCCESS'
export const GET_USER_TEAMS_FAILED = 'GET_USER_TEAMS_FAILED'

export const DELETE_TEAM_MEMBER_REQUEST = 'DELETE_TEAM_MEMBER_REQUEST'
export const DELETE_TEAM_MEMBER_SUCCESS = 'DELETE_TEAM_MEMBER_SUCCESS'
export const DELETE_TEAM_MEMBER_FAILED = 'DELETE_TEAM_MEMBER_FAILED'

export const DELETE_TEAM_REQUEST = 'DELETE_TEAM_REQUEST'
export const DELETE_TEAM_SUCCESS = 'DELETE_TEAM_SUCCESS'
export const DELETE_TEAM_FAILED = 'DELETE_TEAM_FAILED'

export const GET_STICKY_ARTICLES_REQUEST = 'GET_STICKY_ARTICLES_REQUEST'
export const GET_STICKY_ARTICLES_SUCCESS = 'GET_STICKY_ARTICLES_SUCCESS'
export const GET_STICKY_ARTICLES_FAILED = 'GET_STICKY_ARTICLES_FAILED'

export const GET_HOME_USER_DETAIL_REQUEST = 'GET_HOME_USER_DETAIL_REQUEST'
export const GET_HOME_USER_DETAIL_SUCCESS = 'GET_HOME_USER_DETAIL_SUCCESS'
export const GET_HOME_USER_DETAIL_FAILED = 'GET_HOME_USER_DETAIL_FAILED'

export const GET_HOME_USER_LIST_REQUEST = 'GET_HOME_USER_LIST_REQUEST'
export const GET_HOME_USER_LIST_SUCCESS = 'GET_HOME_USER_LIST_SUCCESS'
export const GET_HOME_USER_LIST_FAILED = 'GET_HOME_USER_LIST_FAILED'

export const GET_HOME_TEAM_DETAIL_REQUEST = 'GET_HOME_TEAM_DETAIL_REQUEST'
export const GET_HOME_TEAM_DETAIL_SUCCESS = 'GET_HOME_TEAM_DETAIL_SUCCESS'
export const GET_HOME_TEAM_DETAIL_FAILED = 'GET_HOME_TEAM_DETAIL_FAILED'

export const GET_HOME_TEAM_LIST_REQUEST = 'GET_HOME_TEAM_LIST_REQUEST'
export const GET_HOME_TEAM_LIST_SUCCESS = 'GET_HOME_TEAM_LIST_SUCCESS'
export const GET_HOME_TEAM_LIST_FAILED = 'GET_HOME_TEAM_LIST_FAILED'

export const SET_NAVBAR = 'SET_NAVBAR'
