export const GET_ARTICLES_REQUEST = 'GET_ARTICLES_REQUEST'
export const GET_ARTICLES_SUCCESS = 'GET_ARTICLES_SUCCESS'
export const GET_ARTICLES_FAILED = 'GET_ARTICLES_FAILED'

export const POST_LOGIN_REQUEST = 'POST_LOGIN_REQUEST'
export const POST_LOGIN_SUCCESS = 'POST_LOGIN_SUCCESS'
export const POST_LOGIN_FAILED = 'POST_LOGIN_FAILED'

export const POST_LOGOUT_REQUEST = 'POST_LOGOUT_REQUEST'
export const POST_LOGOUT_SUCCESS = 'POST_LOGOUT_SUCCESS'
export const POST_LOGOUT_FAILED = 'POST_LOGOUT_FAILED'

export const POST_SIGNUP_REQUEST = 'POST_SIGNUP_REQUEST'
export const POST_SIGNUP_SUCCESS = 'POST_SIGNUP_SUCCESS'
export const POST_SIGNUP_FAILED = 'POST_SIGNUP_FAILED'

export const FETCH_REQUEST = 'FETCH_REQUEST'
export const FETCH_SUCCESS = 'FETCH_SUCCESS'
export const FETCH_FAILED = 'FETCH_FAILED'

export const POST_UPLOAD_REQUEST = 'POST_UPLOAD_REQUEST'
export const POST_UPLOAD_SUCCESS = 'POST_UPLOAD_SUCCESS'
export const POST_UPLOAD_FAILED = 'POST_UPLOAD_FAILED'

export const GET_USERINFO_REQUEST = 'GET_USERINFO_REQUEST'
export const GET_USERINFO_SUCCESS = 'GET_USERINFO_SUCCESS'
export const GET_USERINFO_FAILED = 'GET_USERINFO_FAILED'

export const PUT_USERINFO_REQUEST = 'PUT_USERINFO_REQUEST'
export const PUT_USERINFO_SUCCESS = 'PUT_USERINFO_SUCCESS'
export const PUT_USERINFO_FAILED = 'PUT_USERINFO_FAILED'

export const GET_STICKY_ARTICLES_REQUEST = 'GET_STICKY_ARTICLES_REQUEST'
export const GET_STICKY_ARTICLES_SUCCESS = 'GET_STICKY_ARTICLES_SUCCESS'
export const GET_STICKY_ARTICLES_FAILED = 'GET_STICKY_ARTICLES_FAILED'

export const SET_NAVBAR = 'SET_NAVBAR'
